name: demologin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  audioplayers: ^3.0.1
  cloud_firestore: ^4.8.4
  connectivity_plus: ^4.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter_local_notifications: ^15.1.0+1
  speech_to_text: ^6.3.0
  voice_message_package: ^1.0.41
  youtube_player_iframe: ^4.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
